# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c984e487f8c794a677dd20bb1855c3b06dae4b3b7a768a8d83365ae4a6a3ca46f3fbb1d513378ee80ca171ab572e93f78ddc3046f4dbe6697baf9d802a9f82

test:
  secret_key_base: 9dfdbf67f2f11bee395dbb31769bd79f63965a6b3efee5e984ccca243addc6acb7c5712a0acf83aea75a4a09b7944604742f6ef5219191f39b5f608fc7ab2d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
